"""Initial schema

Revision ID: dec32fa40317
Revises: 90f4ea5992b5
Create Date: 2025-03-21 23:33:51.793675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID  # Add this import


# revision identifiers, used by Alembic.
revision: str = 'dec32fa40317'
down_revision: Union[str, None] = '90f4ea5992b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_partners', 'partner_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=False)
    op.alter_column('ai_partners', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=True)
    op.alter_column('events', 'event_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=False)
    op.alter_column('events', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=True)
    op.alter_column('events', 'partner_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=True)
    op.alter_column('gifts', 'gift_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=False)
    op.alter_column('gifts', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=True)
    op.alter_column('gifts', 'partner_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=True)
    op.alter_column('love_rating', 'rating_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=False)
    op.alter_column('love_rating', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=True)
    op.alter_column('love_rating', 'partner_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=True)
    op.alter_column('messages', 'message_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=True)
    op.alter_column('messages', 'partner_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'partner_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('messages', 'user_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('messages', 'message_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('love_rating', 'partner_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('love_rating', 'user_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('love_rating', 'rating_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('gifts', 'partner_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('gifts', 'user_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('gifts', 'gift_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('events', 'partner_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('events', 'user_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('events', 'event_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('ai_partners', 'user_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('ai_partners', 'partner_id',
               existing_type=UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
